### ISSUE TITLE
[FORCE2019] Identifiers for software

### ISSUE THREAD

**Issue by moranegg** [force11/force11-rda-scidwg#1]
Please comment this track if you are interested in **Identifiers for software** with the specific aspects that interests you. 
You can use the list below:
-  Granularity of identification
-  Correspondence between different identifier schemas
-  Hacking the software citation graph
-  Exploring synergies

**Comment by dbouquin** [comment]
Interested in granularity of identification/hacking the citation graph. Also the intersections between this topic and data quality.

**Comment by npch** [comment]
Is anyone interested in working to understand software as part of the PID Graph?

Possible activities might include:
- Understand how PIDs are used to identify and connect different research entities/objects
- Understand what data and datasets are currently available and how to use them
- Exploring and developing tools and APIs for working with PID graphs 
- Creating an example of an “end-to-end” application of the PID graph, e.g. 
  - identifying all other research entities which are directly connected to a piece of software with a PID
  - understanding if particular software and datasets are commonly referenced together

Resources:
- https://blog.datacite.org/using-jupyter-notebooks-with-graphql-and-the-pid-graph/
- https://support.datacite.org/docs/datacite-graphql-api-guide
- https://www.pidforum.org/c/pid-graph

**Comment by moranegg** [comment]
The Identifiers for software track:
    - [Discussion notes](../tree/master/hackathon/FORCE2019/outcomes/track_notes_identifiers.md)
    - [preliminary identifiers crosswalk](../tree/master/hackathon/FORCE2019/outcomes/crosswalk_identifiers.csv)
