### ISSUE TITLE
[FORCE2019] Metadata interoperability

### ISSUE THREAD

**Issue by moranegg** [force11/force11-rda-scidwg#2]
Please comment this track if you are interested in **Metadata interoperability** with the specific aspects that interests you. 
You can use the list below:
- Metadata mapping (CodeMeta)
- Connections with WikiData

**Comment by monperrus** [comment]
It's unclear what is the minimal codemeta JSON file to be put in a repo of a research prototype.

Maybe https://github.com/codemeta/codemeta.github.io/pull/16/files?

**Comment by moranegg** [comment]
CodeMeta tooling

**Comment by dbouquin** [comment]
Connections with WikiData

**Comment by npch** [comment]
The other issue I created #6 (Software in the PID Graph) might better fit as part of this group.

**Comment by moranegg** [comment]
The Metadata interoperability track's outcomes:
  - [Discussion notes](../tree/master/hackathon/FORCE2019/outcomes/track_notes_metadata_interoperability.md)
  - [eLife overview](../tree/master/hackathon/FORCE2019/outcomes/elife_overview.pdf)
  - Tools and Hacks:
    - [CodeMeta and citation tools survey](../tree/master/hackathon/FORCE2019/outcomes/CodeMeta_Citation_tools_survey.csv)
    - An experiment with GitHub actions and Zenodo.     
      - [repository](https://github.com/arfon/zenodo-actions)
    - Cite my code- chrome extension.
      - [repository](https://github.com/NateWr/citemycode) on branch [codemeta_hackathon](https://github.com/NateWr/citemycode/tree/codemeta_hackathon)
    - CodeMeta Generator
      - [repository](https://forge.softwareheritage.org/source/codemeta-generator/)
      - [project board](https://forge.softwareheritage.org/tag/codemeta_generator/)
