### ISSUE TITLE
[FORCE2019]  Policies and incentives

### ISSUE THREAD

**Issue by moranegg** [force11/force11-rda-scidwg#4]
Please comment this track if you are interested in **Policies and incentives** with the specific aspects that interests you.
You can use the list below:
- Institutions
- Evaluation committees
- National research bodies
- Learned societies
 - Publishers

**Comment by dbouquin** [comment]
Interested in the institutions and publisher angles

**Comment by npch** [comment]
People might be interested in the work of the [NISO group on Reproducibility Badging](https://www.niso.org/standards-committees/reproducibility-badging), unfortunately I don't think the drafts of the proposed levels of badging are publicly viewable yet. This might affect the incentives from publishers and learned societies.

**Comment by moranegg** [comment]
The policies and incentives track's outcomes:
  - [Discussion notes](../tree/master/hackathon/FORCE2019/outcomes/track_notes_policies_incentives.md)
